# Generated by Django 5.2.8 on 2025-12-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='GestionSTOCK', max_length=200, verbose_name="Nom de l'entreprise")),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name="Logo de l'entreprise")),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
            ],
            options={
                'verbose_name': 'Paramètres',
                'verbose_name_plural': 'Paramètres',
            },
        ),
    ]
