# Generated by Django 5.2.8 on 2025-12-02 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_point_of_sale(apps, schema_editor):
    """Crée un point de vente par défaut pour la migration"""
    PointOfSale = apps.get_model('inventory', 'PointOfSale')
    if not PointOfSale.objects.exists():
        PointOfSale.objects.create(
            id=1,
            name='Magasin Principal',
            code='MAIN',
            is_warehouse=True,
        )


def reverse_create_default_point_of_sale(apps, schema_editor):
    """Supprime le point de vente par défaut lors d'un rollback"""
    PointOfSale = apps.get_model('inventory', 'PointOfSale')
    PointOfSale.objects.filter(id=1, code='MAIN').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_settings_currency_quote_quoteitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Produit'),
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom du point de vente')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_warehouse', models.BooleanField(default=False, help_text="Cocher si c'est un entrepôt central plutôt qu'un point de vente", verbose_name='Est un entrepôt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Point de vente',
                'verbose_name_plural': 'Points de vente',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(
            create_default_point_of_sale,
            reverse_create_default_point_of_sale,
        ),
        migrations.AddField(
            model_name='inventory',
            name='point_of_sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.pointofsale', verbose_name='Point de vente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_point_of_sale',
            field=models.ForeignKey(default=1, help_text="Point de vente d'origine (pour sorties et transferts)", on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements', to='inventory.pointofsale', verbose_name='De (Point de vente)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_point_of_sale',
            field=models.ForeignKey(blank=True, help_text='Point de vente de destination (pour transferts uniquement)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='inventory.pointofsale', verbose_name='Vers (Point de vente)'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'point_of_sale')},
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'point_of_sale'], name='inventory_i_product_11c5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['point_of_sale'], name='inventory_i_point_o_709f39_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'from_point_of_sale'], name='inventory_s_product_863006_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_ed5291_idx'),
        ),
        migrations.AddIndex(
            model_name='pointofsale',
            index=models.Index(fields=['code'], name='inventory_p_code_2ce889_idx'),
        ),
        migrations.AddIndex(
            model_name='pointofsale',
            index=models.Index(fields=['is_active'], name='inventory_p_is_acti_baee76_idx'),
        ),
    ]
