# Generated by Django 5.2.8 on 2025-12-02 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_product_pointofsale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, help_text="Point de vente d'où provient cette facture", null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.pointofsale', verbose_name='Point de vente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Indique si le stock a déjà été déduit pour cette facture', verbose_name='Stock déduit'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, help_text='Point de vente où les marchandises sont reçues', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.pointofsale', verbose_name='Point de vente'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='stock_added',
            field=models.BooleanField(default=False, help_text='Indique si le stock a déjà été ajouté pour ce bon', verbose_name='Stock ajouté'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, help_text='Point de vente où travaille cet utilisateur', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.pointofsale', verbose_name='Point de vente assigné'),
        ),
    ]
