# Generated by Django 5.2.8 on 2025-12-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_invoice_point_of_sale_invoice_stock_deducted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('retail', 'Vente au détail'), ('wholesale', 'Vente en gros')], default='retail', max_length=20, verbose_name='Type de vente'),
        ),
    ]
