# Generated by Django 5.2.8 on 2025-12-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_setup_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='apply_tax',
            field=models.BooleanField(default=True, verbose_name='Appliquer TVA'),
        ),
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marge bénéficiaire en pourcentage', max_digits=5, verbose_name='Marge (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat"),
        ),
    ]
