# Generated by Django 5.2.8 on 2025-12-06 01:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_invoice_apply_tax_product_margin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.01, help_text='Prix de vente calculé automatiquement (PUA × (1 + marge/100)) ou saisi manuellement', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix de vente unitaire (PVU)'),
            preserve_default=False,
        ),
    ]
