# Generated by Django 5.2.8 on 2025-12-10 07:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models




def convert_margin_percentage_to_amount(apps, schema_editor):
    """Convert existing margin percentages to amounts"""
    Product = apps.get_model('inventory', 'Product')
    
    for product in Product.objects.all():
        if product.margin and product.purchase_price:
            # Convert: margin_amount = purchase_price × (margin_percentage / 100)
            margin_amount = product.purchase_price * (product.margin / Decimal('100'))
            product.margin = margin_amount.quantize(Decimal('0.01'))
            product.save(update_fields=['margin'])


def reverse_margin_amount_to_percentage(apps, schema_editor):
    """Reverse migration: convert amounts back to percentages"""
    Product = apps.get_model('inventory', 'Product')
    
    for product in Product.objects.all():
        if product.margin and product.purchase_price and product.purchase_price > 0:
            # Convert back: margin_percentage = (margin_amount / purchase_price) × 100
            margin_percentage = (product.margin / product.purchase_price) * Decimal('100')
            product.margin = margin_percentage.quantize(Decimal('0.01'))
            product.save(update_fields=['margin'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_rename_unit_price_to_selling_price'),
    ]

    operations = [
        # First, convert the data while the field is still percentage
        migrations.RunPython(
            convert_margin_percentage_to_amount,
            reverse_margin_amount_to_percentage
        ),
        # Then, alter the field schema
        migrations.AlterField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marge bénéficiaire en montant (GNF)', max_digits=10, verbose_name='Marge bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Prix de vente calculé automatiquement (PUA + marge) ou saisi manuellement', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix de vente unitaire (PVU)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(choices=[('GNF', 'Franc Guinéen (GNF)')], default='GNF', max_length=3, verbose_name='Devise'),
        ),
    ]
