# Generated by Django 5.2.8 on 2025-12-12 06:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_convert_margin_to_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='delivery_costs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Frais de transport, douane, etc. à repartir sur le coût des produits', max_digits=20, verbose_name='Frais de livraison'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Sous-total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Montant TVA'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total TTC'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Sous-total'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Montant TVA'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total TTC'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Coût unitaire'),
        ),
    ]
