# Generated by Django 5.2.8 on 2025-12-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_receipt_delivery_costs_alter_invoice_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Remise (%)'),
        ),
    ]
