# Generated by Django 5.2.8 on 2025-12-20 02:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_invoiceitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='is_wholesale',
            field=models.BooleanField(default=False, verbose_name='Vendu en gros lot'),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_box',
            field=models.PositiveIntegerField(default=1, help_text="Nombre d'articles dans un carton/gros lot", verbose_name='Unités par carton'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Marge (Gros)'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat (Gros)"),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de vente (Gros)'),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='is_wholesale',
            field=models.BooleanField(default=False, verbose_name='Reçu en gros lot'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Prix de vente unitaire au détail', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix de vente (Détail)'),
        ),
    ]
