# Generated by Django 5.2.8 on 2025-12-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_invoiceitem_is_wholesale_product_units_per_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_type',
            field=models.CharField(choices=[('retail', 'Vente au détail'), ('wholesale', 'Vente en gros')], default='retail', max_length=20, verbose_name='Type de devis'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='is_wholesale',
            field=models.BooleanField(default=False, verbose_name='Vendu en gros lot'),
        ),
    ]
