# Generated by Django 5.2.8 on 2025-12-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_add_product_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units_per_box',
            field=models.PositiveIntegerField(default=1, help_text="Nombre d'articles dans un colis, casier ou carton", verbose_name='Unités par colis/casier/carton'),
        ),
    ]
