# Generated by Django 5.2.8 on 2026-01-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_invoice_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='is_wholesale',
            field=models.BooleanField(default=False, verbose_name='En gros lot'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='is_wholesale',
            field=models.BooleanField(default=True, verbose_name='Reçu en gros lot'),
        ),
    ]
