# Generated by Django 5.2.8 on 2026-01-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_stockmovement_is_wholesale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='is_wholesale',
        ),
    ]
