# Generated by Django 5.2.8 on 2026-01-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_quoteitem_is_wholesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='is_wholesale',
            field=models.BooleanField(default=False, verbose_name='Vendu en gros lot'),
        ),
    ]
