# Generated by Django 5.2.8 on 2026-01-02 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_quoteitem_is_wholesale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Montant')),
                ('date', models.DateField(verbose_name='Date de la dépense')),
                ('description', models.TextField(verbose_name='Description/Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pointofsale', verbose_name='Point de vente')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.expensecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyProfitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Mois (1-12)')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('total_sales_brut', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Ventes Brutes (Avant Remises)')),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Remises Accordées')),
                ('total_cost_of_goods', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="Coût d'Achat Total (COGS)")),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Charges (Loyer, Salaires, etc.)')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Bénéfice Brut')),
                ('net_interest', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Intérêt Net')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pointofsale', verbose_name='Point de vente')),
            ],
            options={
                'verbose_name': 'Rapport de profit mensuel',
                'verbose_name_plural': 'Rapports de profit mensuels',
                'ordering': ['-year', '-month', 'point_of_sale'],
                'unique_together': {('month', 'year', 'point_of_sale')},
            },
        ),
    ]
