# Generated by Django 5.2.8 on 2026-01-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_expensecategory_expense_monthlyprofitreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Bénéfice Total'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Marge'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="Prix d'achat unitaire"),
        ),
    ]
