# Generated by Django 5.1.4 on 2026-01-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_invoice_total_profit_invoiceitem_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_order_type',
            field=models.CharField(choices=[('retail', 'Détail'), ('wholesale', 'Gros')], default='retail', max_length=20, verbose_name='Type de vente par défaut'),
        ),
        migrations.AddField(
            model_name='settings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux de TVA (%)'),
        ),
    ]
