# Generated by Django 5.1.4 on 2026-01-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_settings_default_order_type_settings_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='daily_reports',
            field=models.BooleanField(default=True, verbose_name='Rapports journaliers'),
        ),
        migrations.AddField(
            model_name='settings',
            name='new_customer_notifications',
            field=models.BooleanField(default=False, verbose_name='Notifications nouveaux clients'),
        ),
    ]
