# Generated by Django 5.1.4 on 2026-01-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_settings_daily_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='smart_rounding',
            field=models.BooleanField(default=True, verbose_name='Arrondi intelligent'),
        ),
    ]
