# Generated by Django 5.1.4 on 2026-01-21 05:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_settings_smart_rounding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'CatÃ©gorie', 'verbose_name_plural': 'CatÃ©gories'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'DÃ©pense', 'verbose_name_plural': 'DÃ©penses'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name': 'CatÃ©gorie de dÃ©pense', 'verbose_name_plural': 'CatÃ©gories de dÃ©penses'},
        ),
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Code de rÃ©initialisation', 'verbose_name_plural': 'Codes de rÃ©initialisation'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-date_received'], 'verbose_name': 'Bon de rÃ©ception', 'verbose_name_plural': 'Bons de rÃ©ception'},
        ),
        migrations.AlterModelOptions(
            name='receiptitem',
            options={'verbose_name': 'Ligne de bon de rÃ©ception', 'verbose_name_plural': 'Lignes de bon de rÃ©ception'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'ParamÃ¨tres', 'verbose_name_plural': 'ParamÃ¨tres'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='daily_reports',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='default_order_type',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='new_customer_notifications',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='smart_rounding',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de crÃ©ation'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='DerniÃ¨re modification'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de crÃ©ation'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='NumÃ©ro fiscal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='DerniÃ¨re modification'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.expensecategory', verbose_name='CatÃ©gorie'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='CrÃ©Ã© par'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Date de la dÃ©pense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='RÃ©fÃ©rence'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom de la catÃ©gorie'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='DerniÃ¨re mise Ã\xa0 jour'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='QuantitÃ©'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reorder_level',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seuil de rÃ©approvisionnement'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de crÃ©ation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='CrÃ©Ã© par'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_due',
            field=models.DateField(verbose_name="Date d'Ã©chÃ©ance"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(verbose_name="Date d'Ã©mission"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='NumÃ©ro de facture'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('retail', 'Vente au dÃ©tail'), ('wholesale', 'Vente en gros')], default='retail', max_length=20, verbose_name='Type de vente'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, help_text="Point de vente d'oÃ¹ provient cette facture", null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.pointofsale', verbose_name='Point de vente'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'EnvoyÃ©e'), ('paid', 'PayÃ©e'), ('cancelled', 'AnnulÃ©e')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Indique si le stock a dÃ©jÃ\xa0 Ã©tÃ© dÃ©duit pour cette facture', verbose_name='Stock dÃ©duit'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='BÃ©nÃ©fice Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='DerniÃ¨re modification'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='QuantitÃ©'),
        ),
        migrations.AlterField(
            model_name='monthlyprofitreport',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='BÃ©nÃ©fice Brut'),
        ),
        migrations.AlterField(
            model_name='monthlyprofitreport',
            name='net_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='IntÃ©rÃªt Net'),
        ),
        migrations.AlterField(
            model_name='monthlyprofitreport',
            name='total_cost_of_goods',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="CoÃ»t d'Achat Total (COGS)"),
        ),
        migrations.AlterField(
            model_name='monthlyprofitreport',
            name='total_discounts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Remises AccordÃ©es'),
        ),
        migrations.AlterField(
            model_name='monthlyprofitreport',
            name='year',
            field=models.IntegerField(verbose_name='AnnÃ©e'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Code de vÃ©rification'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de crÃ©ation'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='used',
            field=models.BooleanField(default=False, verbose_name='UtilisÃ©'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='EnregistrÃ© par'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'EspÃ¨ces'), ('bank_transfer', 'Virement bancaire'), ('check', 'ChÃ¨que'), ('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='RÃ©fÃ©rence'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de crÃ©ation'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='is_warehouse',
            field=models.BooleanField(default=False, help_text="Cocher si c'est un entrepÃ´t central plutÃ´t qu'un point de vente", verbose_name='Est un entrepÃ´t'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='DerniÃ¨re modification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='CatÃ©gorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de crÃ©ation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marge bÃ©nÃ©ficiaire en montant (GNF)', max_digits=10, verbose_name='Marge bÃ©nÃ©ficiaire'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Prix de vente unitaire au dÃ©tail', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix de vente (DÃ©tail)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_per_box',
            field=models.PositiveIntegerField(default=1, help_text="Nombre d'articles dans un colis, casier ou carton", verbose_name='UnitÃ©s par colis/casier/carton'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='DerniÃ¨re modification'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de crÃ©ation'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='CrÃ©Ã© par'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_issued',
            field=models.DateField(verbose_name="Date d'Ã©mission"),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='NumÃ©ro de devis'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_type',
            field=models.CharField(choices=[('retail', 'Vente au dÃ©tail'), ('wholesale', 'Vente en gros')], default='retail', max_length=20, verbose_name='Type de devis'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'EnvoyÃ©'), ('accepted', 'AcceptÃ©'), ('rejected', 'RejetÃ©'), ('converted', 'Converti en facture')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='DerniÃ¨re modification'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(verbose_name='Date de validitÃ©'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='QuantitÃ©'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de crÃ©ation'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='CrÃ©Ã© par'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_received',
            field=models.DateField(verbose_name='Date de rÃ©ception'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='delivery_costs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Frais de transport, douane, etc. Ã\xa0 repartir sur le coÃ»t des produits', max_digits=20, verbose_name='Frais de livraison'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, help_text='Point de vente oÃ¹ les marchandises sont reÃ§ues', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.pointofsale', verbose_name='Point de vente'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='NumÃ©ro de bon'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('received', 'ReÃ§u'), ('validated', 'ValidÃ©')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='stock_added',
            field=models.BooleanField(default=False, help_text='Indique si le stock a dÃ©jÃ\xa0 Ã©tÃ© ajoutÃ© pour ce bon', verbose_name='Stock ajoutÃ©'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='supplier_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='RÃ©fÃ©rence fournisseur'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='DerniÃ¨re modification'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='is_wholesale',
            field=models.BooleanField(default=True, verbose_name='ReÃ§u en gros lot'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='QuantitÃ©'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.receipt', verbose_name='Bon de rÃ©ception'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='CoÃ»t unitaire'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(choices=[('GNF', 'Franc GuinÃ©en (GNF)')], default='GNF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='language',
            field=models.CharField(choices=[('fr', 'FranÃ§ais'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entry', 'EntrÃ©e'), ('exit', 'Sortie'), ('adjustment', 'Ajustement'), ('transfer', 'Transfert'), ('return', 'Retour'), ('defective', 'DÃ©fectueux')], max_length=20, verbose_name='Type de mouvement'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='QuantitÃ©'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='RÃ©fÃ©rence'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de crÃ©ation'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='DerniÃ¨re modification'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, help_text='Point de vente oÃ¹ travaille cet utilisateur', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.pointofsale', verbose_name='Point de vente assignÃ©'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('Succèss', 'Succès'), ('error', 'Erreur')], default='info', max_length=20, verbose_name='Type')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
