# Generated by Django 5.1.4 on 2026-01-22 20:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_fix_pos_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie de dépense', 'verbose_name_plural': 'Catégories de dépenses'},
        ),
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Code de réinitialisation', 'verbose_name_plural': 'Codes de réinitialisation'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-date_received'], 'verbose_name': 'Bon de réception', 'verbose_name_plural': 'Bons de réception'},
        ),
        migrations.AlterModelOptions(
            name='receiptitem',
            options={'verbose_name': 'Ligne de bon de réception', 'verbose_name_plural': 'Lignes de bon de réception'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Paramètres', 'verbose_name_plural': 'Paramètres'},
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=5, help_text='Le stock est considéré comme faible en dessous de ce seuil', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seuil de réapprovisionnement'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro fiscal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.expensecategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Date de la dépense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise Ã\xa0 jour'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reorder_level',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seuil de réapprovisionnement'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_due',
            field=models.DateField(verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(verbose_name="Date d'émission"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('retail', 'Vente au détail'), ('wholesale', 'Vente en gros')], default='retail', max_length=20, verbose_name='Type de vente'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Indique si le stock a déjÃ\xa0 été déduit pour cette facture', verbose_name='Stock déduit'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Bénéfice Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='monthlyprofitreport',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Bénéfice Brut'),
        ),
        migrations.AlterField(
            model_name='monthlyprofitreport',
            name='net_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Intérêt Net'),
        ),
        migrations.AlterField(
            model_name='monthlyprofitreport',
            name='total_cost_of_goods',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="Coût d'Achat Total (COGS)"),
        ),
        migrations.AlterField(
            model_name='monthlyprofitreport',
            name='total_discounts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Remises Accordées'),
        ),
        migrations.AlterField(
            model_name='monthlyprofitreport',
            name='year',
            field=models.IntegerField(verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Code de vérification'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Utilisé'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='is_warehouse',
            field=models.BooleanField(default=False, help_text="Cocher si c'est un entrepôt central plutôt qu'un point de vente", verbose_name='Est un entrepôt'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marge bénéficiaire en montant (GNF)', max_digits=10, verbose_name='Marge bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Prix de vente unitaire au détail', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix de vente (Détail)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_per_box',
            field=models.PositiveIntegerField(default=1, help_text="Nombre d'articles dans un colis, casier ou carton", verbose_name='Unités par colis/casier/carton'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_issued',
            field=models.DateField(verbose_name="Date d'émission"),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro de devis'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_type',
            field=models.CharField(choices=[('retail', 'Vente au détail'), ('wholesale', 'Vente en gros')], default='retail', max_length=20, verbose_name='Type de devis'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('converted', 'Converti en facture')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(verbose_name='Date de validité'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_received',
            field=models.DateField(verbose_name='Date de réception'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='delivery_costs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Frais de transport, douane, etc. Ã\xa0 repartir sur le coût des produits', max_digits=20, verbose_name='Frais de livraison'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, help_text='Point de vente oÃ¹ les marchandises sont reçues', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.pointofsale', verbose_name='Point de vente'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro de bon'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('received', 'Reçu'), ('validated', 'Validé')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='stock_added',
            field=models.BooleanField(default=False, help_text='Indique si le stock a déjÃ\xa0 été ajouté pour ce bon', verbose_name='Stock ajouté'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='supplier_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence fournisseur'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='is_wholesale',
            field=models.BooleanField(default=True, verbose_name='Reçu en gros lot'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.receipt', verbose_name='Bon de réception'),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Coût unitaire'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(choices=[('GNF', 'Franc Guinéen (GNF)')], default='GNF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entry', 'Entrée'), ('exit', 'Sortie'), ('adjustment', 'Ajustement'), ('transfer', 'Transfert'), ('return', 'Retour'), ('defective', 'Défectueux')], max_length=20, verbose_name='Type de mouvement'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, help_text='Point de vente oÃ¹ travaille cet utilisateur', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.pointofsale', verbose_name='Point de vente assigné'),
        ),
    ]
