# Generated by Django 5.1.4 on 2026-01-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_category_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='daily_reports',
            field=models.BooleanField(default=False, verbose_name='Rapports journaliers'),
        ),
        migrations.AddField(
            model_name='settings',
            name='default_order_type',
            field=models.CharField(choices=[('retail', 'Détail'), ('wholesale', 'Gros')], default='retail', max_length=20, verbose_name='Type de vente par défaut'),
        ),
        migrations.AddField(
            model_name='settings',
            name='new_customer_notifications',
            field=models.BooleanField(default=False, verbose_name='Notifications nouveaux clients'),
        ),
        migrations.AddField(
            model_name='settings',
            name='smart_rounding',
            field=models.BooleanField(default=False, verbose_name='Arrondi intelligent'),
        ),
        migrations.AddField(
            model_name='settings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='Taux TVA (%)'),
        ),
    ]
