# Generated by Django 5.1.4 on 2026-01-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofsale',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du Gérant (Texte)'),
        ),
    ]
