# Generated by Django 5.1.4 on 2026-01-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_pointofsale_manager_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='apply_tax',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total'),
        ),
    ]
