# Generated by Django 5.1.4 on 2026-01-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_remove_invoice_apply_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Remise globale'),
        ),
    ]
