# Generated by Django 5.1.4 on 2026-01-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_invoice_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='apply_tax',
            field=models.BooleanField(default=False, verbose_name='Appliquer la taxe'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Montant de la taxe'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='Taux de taxe (%)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Montant de la taxe'),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='Taux de taxe (%)'),
        ),
    ]
