# Generated by Django 5.1.4 on 2026-01-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_invoice_apply_tax_invoice_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5, verbose_name='Taux de taxe (%)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5, verbose_name='Taux de taxe (%)'),
        ),
    ]
