# Generated by Django 5.1.4 on 2026-01-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_alter_invoice_tax_rate_alter_quote_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='apply_tax',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(verbose_name="Valide jusqu'au"),
        ),
    ]
