# Generated by Django 5.2.8 on 2025-12-18 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0016_alter_invoiceitem_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Personne de contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='RDC', max_length=100, verbose_name='Pays')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de bon')),
                ('date_received', models.DateField(verbose_name='Date de réception')),
                ('supplier_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence fournisseur')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('received', 'Reçu'), ('validated', 'Validé')], default='draft', max_length=20, verbose_name='Statut')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Montant total')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('delivery_costs', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Frais de livraison')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchasing_receipts_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('point_of_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_receipts', to='inventory.pointofsale', verbose_name='Point de vente')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_receipts', to='purchasing.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Bon de réception',
                'verbose_name_plural': 'Bons de réception',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Coût unitaire')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Coût total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_receipt_items', to='inventory.product', verbose_name='Produit')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.receipt', verbose_name='Bon de réception')),
            ],
            options={
                'verbose_name': 'Ligne de réception',
                'verbose_name_plural': 'Lignes de réception',
            },
        ),
    ]
