# Generated by Django 5.2.8 on 2025-12-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='point_of_sale',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='ReceiptItem',
        ),
    ]
