# Generated by Django 5.2.8 on 2025-12-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
