# Generated by Django 5.1.4 on 2026-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_order_amount_paid_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Indique si le stock a déjà été déduit pour cette commande', verbose_name='Stock déduit'),
        ),
    ]
