# Generated by Django 5.1.4 on 2026-01-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_order_stock_deducted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('pending', 'En attente'), ('validated', 'Validée'), ('processing', 'En préparation'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut de la commande'),
        ),
    ]
