# Generated by Django 5.1.4 on 2026-01-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_order_tax_amount_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='walk_in_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du client (Passage)'),
        ),
        migrations.AddField(
            model_name='order',
            name='walk_in_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone (Passage)'),
        ),
    ]
