# Generated by Django 5.1.4 on 2026-01-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_order_walk_in_name_order_walk_in_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Remise globale'),
        ),
    ]
