# Generated by Django 5.1.4 on 2026-01-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_order_tax_amount_order_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5, verbose_name='Taux de taxe (%)'),
        ),
    ]
