# Generated by Django 5.1.4 on 2026-01-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_order_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_rate',
        ),
    ]
